cvs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from products import views

urlpatterns = [
    path('', views.index),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:store_pk>/detail/', views.detail, name='detail'),
    path('<int:pk>/create/', views.create, name='create'),
    path('<int:store_pk>/<int:item_pk>/item_detail', views.item_detail, name='item_detail'),
    path('<int:store_pk>/<int:item_pk>/edit', views.edit, name='edit'),
    path('<int:store_pk>/<int:item_pk>/delete', views.delete, name='delete'),
]

products/models.py
from django.db import models

# Create your models here.
class Store(models.Model):
    name = models.CharField(max_length=20)
    manager = models.CharField(max_length=20)
    image = models.ImageField(default='/media/ghost.jpeg')

    def __str__(self):
        return self.name

class Company(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Incharge(models.Model):
    SEX_SELECT = (
        ('M', 'Male'),
        ('F', 'Female'),
        )
    name = models.CharField(max_length=10)
    sex = models.CharField(max_length=1, choices=SEX_SELECT)
    age = models.IntegerField()
    goods = models.ManyToManyField(Store, through='Item')

    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=20)
    image = models.ImageField(default='/media/ghost.jpeg')
    stock = models.IntegerField()
    category = models.CharField(max_length=20)
    company = models.ForeignKey(Company, on_delete=models.PROTECT)
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    incharge = models.ForeignKey(Incharge, on_delete=models.CASCADE)

    class Meta:
        ordering = ('category',)

    # def get_image(self):
    #     if self.image:
    #         return self.image.url
    #     else:
    #         return '/media/ghost.jpeg'

products/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = "__all__"

products/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from .models import Store, Company, Incharge, Item
from .forms import ItemForm

# Create your views here.
def index(request):
    stores = Store.objects.all()
    context = {
        'stores':stores,
    }
    return render(request, 'products/index.html', context)

def detail(request, store_pk):
    store = Store.objects.get(id=store_pk)
    context = {
        'store':store,
    }
    return render(request, 'products/detail.html', context)

def create(request, pk):
    store = Store.objects.get(id=pk)
    if request.method=="POST":
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('products:detail', pk)
    else:
        form = ItemForm()
    context = {
        'form':form,
        'store':store
    }
    return render(request, 'products/form.html', context)


def item_detail(request, store_pk, item_pk):
    store = Store.objects.get(id=store_pk)
    item = Item.objects.get(id=item_pk)
    context = {
        'store': store,
        'item': item,
    }
    return render(request, 'products/item_detail.html', context)

def edit(request, store_pk, item_pk):
    store = Store.objects.get(id=store_pk)
    item = Item.objects.get(id=item_pk)
    if request.method=="POST":
        form = ItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('products:item_detail', store_pk, item_pk)
    else:
        form = ItemForm(instance=item)
    context = {
        'form':form,
        'store':store,
    }
    return render(request, 'products/form.html', context)

def delete(request, store_pk, item_pk):
    store = Store.objects.get(id=store_pk)
    item = Item.objects.get(id=item_pk)
    item.delete()
    return redirect('products:detail', store_pk)

products/templates/products/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  {% if store.item_set.all %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>OUT of STOCK!</strong> You should reorder
    {% for item in store.item_set.all %}
        {% if item.stock <= 5 %}
          {{ item.name }}
            {% if forloop.last %}
            {% else %}
            ,
            {% endif %}
        {% endif %}
    {% endfor %}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
<h3>{{ store.name }} Stock List</h3>
<br>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">NAME</th>
        <th scope="col">STOCK</th>
        <th scope="col">INCHARGE</th>
      </tr>
    </thead>
    <tbody>
      {% for item in store.item_set.all %}
      <tr>
        <th scope="row" >{{ item.id }}</th>
        <td><a href="{% url 'products:item_detail' store.id item.id %}">{{ item.name }}</a></td>
        {% if item.stock <= 5 %}
          <td class="text-danger">{{ item.stock }}</td>
        {% else %}
          <td>{{ item.stock }}</td>
        {% endif %}
        <td>{{ item.incharge }}</td>
      </tr>
       {% endfor %}
    </tbody>
  </table>
  <br>
  <a href="{% url 'products:index' %}"><button class="btn btn-secondary">BACK</button></a>
  <a href="{% url 'products:create' store.id %}"><button class="btn btn-primary">ADD</button></a>
{% endblock %}

products/templates/products/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    {% if request.resolver_match.url_name == 'create' %}
        <h3>새 품목 추가하기</h3>
    {% else %}
        <h3>품목 수정하기</h3>
     {% endif %}
        <div>
            <form action="" method="POST" id="my-form" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
            </form>
            <a href="{% url 'products:detail' store.id %}"><button class="btn btn-secondary">BACK</button></a>
            <button class="btn btn-primary" form="my-form">SUBMIT</button>
        </div>

{% endblock %}

products/templates/products/index.html
{% extends 'base.html' %}
{% load static%}

{% block content %}
  <div class="d-flex justify-content-between">
      <h3>Branch List</h3>
      <img src="{% static 'kakao.png' %}" height="150" class="px-5 mb-3">
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">지점명</th>
        <th scope="col">점장</th>
      </tr>
    </thead>
      {% for store in stores %}
      <tbody>
        <tr height="80">
          <td><a href="#" id="storeId" data-toggle="modal" data-target="#detailModal{{ store.id }}" data-title="data">{{ store.name }}</a></td>
          <td>{{ store.manager }}</td>
        </tr>
      </tbody>
      <div class="modal fade" id="detailModal{{ store.id }}" tabindex="-1" role="dialog" aria-labelledby="detailModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <div class="card text-white bg-secondary" id ="exampleCard" style="width: 30rem;">
                <img  id="detailModalLabel" src="{{ store.image.url }}" class="card-img-top" alt="store image">
                <div class="card-body">
                  <h5 class="card-title" id="detailModalLabel">{{ store.name }}</h5>
                  <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content</p>
                  <a href="{% url 'products:detail' store.id %}" class="btn btn-warning">See in detail</a>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
    {% endfor %}
{% endblock %}

products/templates/products/item_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<h3>{{ store.name }} Stock List</h3>
<hr>
<h4>About {{ item.name }}</h4>
    {% if item.image %}
        <img src="{{ item.image.url }}">
    {% else %}
        <img src="/media/ghost.jpeg" alt="no image">
    {% endif %}
    <br>
    <br>
    <p>STOCK : {{ item.stock }}</p>
    <p>CATEGORY : {{ item.category }}</p>
    <p>COMPANY : {{ item.company }}</p>
    <p>INCHARGE : {{ item.incharge }}</p>
    <br>
    <a href="{% url 'products:detail' store.id %}"><button class="btn btn-secondary">BACK</button></a>
    <a href="{% url 'products:edit' store.id item.id %}"><button class="btn btn-success">EDIT</button></a>
    <a href="{% url 'products:delete' store.id item.id %}"><button class="btn btn-danger">DELETE</button></a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>역삼동 편의점 재고관리</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% bootstrap_css %}
</head>
<body>
    <nav class="navbar navbar-light bg-light mb-2 fixed-top">
      <a class="navbar-brand" href="{% url 'products:index' %}">
        <img src="{% static 'android-chrome-512x512.png' %}" width="30" height="30" class="d-inline-block align-top" alt="logo">
        CU
      </a>
        <ul class="navbar-nav">
          <div class="navbar-brand d-flex align-items-center">역삼동 District Manager의 재고관리 페이지</div>
        </ul>
    </nav>
    <div class='container mt-5 pt-3'>
        {% block content %}
        {% endblock %}
    </div>
    {% bootstrap_javascript jquery='full' %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>